### PR TITLE
Add HeaderInterface

### PR DESCRIPTION
**Pull request by chadicus**
This pull request moves the constants to a `HeaderInterface`. Doing so will allow classes to inherit the constant values much like the [StatusCodeInterface](https://github.com/php-fig/http-message-util/blob/master/src/StatusCodeInterface.php) provided by [fig/http-message-utils](https://github.com/php-fig/http-message-util)

I have also updated the `Header` class to implement the `HeaderInterface` so this change is completely backwards compatible.

### CODE REVIEW

**Comment by MortalFlesh** [comment]
Hello,

first of all, thank you for this PR and interesting idea :+1: .

From my point of view, it could not harm anyone to have an `Interface` for storing constants like that.

But to use that interface as a "_shortcut_" for accessing those constants. It's a whole different story ... I personally would not do it. For planty of reasons.. It hides the information, that the constant is a `Header` constant and it is not that explicit. Which might be harder for new comers or begginers who don't know all headers. It could also conflicts with other constants in `Example` class, which might be a problem. And it even allows to use your `Example` class where `Header[Interface]` is needed, which is not correct. It also allows others to use you `Example` class as header constants source, which adds unwanted coupling (`header(Example::CONTENT_TYPE . ': application/pdf');`).

So as I said on the beginning - my thumb is up for this change, but I would strongly discourage anyone to use it as an interface to implement that way you showed.

---
Btw. please add some information to the `CHANGELOG.md` too

**Comment by jirinovak** [comment]
Hi, thanks for your PR 👍.

I agree with @MortalFlesh. So what about removing problematic part about implementig `HeaderInterface` from `README.md`? Would you please make this change?

**Comment by OndraM** [comment]
Hi, I agree with what has been said about using interface as a shortcut to access the constants. This is known in Java as [constant interface](https://en.wikipedia.org/wiki/Constant_interface), and is considered an antipattern by many.

To be honest, I've never seen any use of this in PHP, so I'm not convicted this is a good idea. Using `Header::CONTENT_TYPE` is as good as `self::CONTENT_TYPE`, but easier to read and without polluting the class namespace. So if @MortalFlesh and @jirinovak agree there is no usecase for this "shortcut" and it should not be used like this, why should we even change it and allow this "anti-pattern" usage?

BTW @chadicus thanks for the hard work with adding the references to the phpdoc, we will definitely use it!

**Comment by chadicus** [comment]
@MortalFlesh @jirinovak @OndraM, I'm closing the PR, but i did open #5  which keeps the added phpdoc

**Pull request closed without merging**
